name: "blackduck-report-action"
description: "Create Black Duck Report and download it"
author: "Jeroen Knoops <jeroen.knoops@philips.com>"
branding:
  icon: "anchor"
  color: "gray-dark"
inputs:
  blackduck-url:
    description: "url to Black Duck instance"
    required: true
  blackduck-token:
    description: "Black Duck API token"
    required: true
  project:
    description: "Project name in Black Duck"
    required: true
  version:
    description: "Version in Black Duck"
    required: true
  report-format:
    description: 'sbomType "SPDX_22", "SPDX_23", "SPDX_30" allows reportFormat values of "JSON", "RDF", "TAGVALUE" or "YAML". sbomType "CYCLONEDX_13", "CYCLONEDX_14", "CYCLONEDX_15", "CYCLONEDX_16" allows reportFormat values of "JSON". sbomType "VERSION_LICENSE" allows reportFormat value "TEXT".'
    default: "JSON"
  sbom-type:
    description: "Type of SBOM report. Allowed values - SPDX_22, SPDX_23, SPDX_30, CYCLONEDX_13, CYCLONEDX_14, CYCLONEDX_15, CYCLONEDX_16, or VERSION_LICENSE"
    default: "SPDX_22"
  blackduck-root-cert:
    description: "CA of self-signed certificate"
    required: false
outputs:
  sbom-file:
    description: "SBOM filename if created"
  sbom-contents:
    description: "SBOM content if created"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.blackduck-url }}
    - ${{ inputs.blackduck-token }}
    - ${{ inputs.project }}
    - ${{ inputs.version }}
    - ${{ inputs.sbom-type }}
    - ${{ inputs.report-format }}
    - ${{ inputs.blackduck-root-cert }}
